CREATE TABLE GAMES (
game_name VARCHAR2(45),
game_date  Date,
p_id INT
);

CREATE TABLE Player(
P_id INT,
P_name VARCHAR(2),
p_gender CHAR(1),
p_age INT,
game_name VARCHAR2(45)
);

ALTER TABLE PLAYER ADD CONSTRAINT Pk_players PRIMARY KEY (P_id); 
ALTER TABLE GAMES ADD CONSTRAINT Pk_games PRIMARY KEY (game_name);
ALTER TABLE PLAYER DROP CONSTRAINT chk_gen;
ALTER TABLE PLAYER ADD CONSTRAINT chk_gen CHECK (p_gender = 'M' || 'F');
ALTER TABLE PLAYER DROP CONSTRAINT chk_gen;
ALTER TABLE PLAYER ADD CONSTRAINT chk_age CHECK (p_age > 17);
ALTER TABLE GAMES ADD CONSTRAINT Fk_player FOREIGN KEY (p_id) REFERENCES PLAYER (p_id);
ALTER TABLE PLAYER ADD CONSTRAINT Fk_Games FOREIGN KEY (game_name) REFERENCES GAMES (game_name);
ALTER TABLE PLAYER MODIFY p_name VARCHAR2(45);

ALTER TABLE GAMES DROP CONSTRAINT Fk_player;
ALTER TABLE PLAYER DROP CONSTRAINT Fk_Games;


INSERT INTO PLAYER (p_id, p_name, p_gender, p_age, game_name)
VALUES 
(1,'Azhar','M',19,'Table Tennis');

INSERT INTO GAMES (game_name, p_id)
VALUES 
('Table Tennis', 1);


--------------------------------------------------------------------------
----------------------------------------------




CREATE TABLE goods (
    goods_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    goods_name VARCHAR2(100) NOT NULL,
    category VARCHAR2(50),
    price NUMBER(10,2),
    stock_quantity NUMBER,
    added_date DATE DEFAULT SYSDATE
);

CREATE TABLE CONSUMER(
c_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
c_fname VARCHAR2(45),
c_lname VARChAR2(45),
goods_id NUMBER,
p_date DATE,
CONSTRAINT fk_goods FOREIGN KEY (goods_id) REFERENCES goods (goods_id)
);

desc CONSUMER;

ALTER TABLE CONSUMER ADD CONSTRAINT chk_date CHECK (p_date >= '12/OCT/2000' AND p_date <= '12/OCT/2025');

INSERT INTO CONSUMER(c_fname, c_lname, goods_id, p_date) 
VALUES
('John', 'Warner', '2', '12/OCT/2025');

INSERT INTO CONSUMER(c_fname, c_lname, goods_id, p_date)
VALUES 
('Will', 'Smith', '2', '13/OCT/2025');

INSERT INTO CONSUMER(c_fname, c_lname, goods_id, p_date)
VALUES              -----------------------not inserted Unique key voilated.------------------
('Will', 'Smith', '6', '12/OCT/2025');



SELECT * FROM CONSUMER;


-------------------CONSTRAINTS-------------------

ALTER TABLE CONSUMER 
ADD CONSTRAINT unk_con ----------------UNIQUE FIRST NAME AND LAST NAME
UNIQUE (c_fname, c_lname);

INSERT INTO goods (goods_name, category, price, stock_quantity)
VALUES ('Laptop HP Pavilion', 'Electronics', 125000.00, 10);

INSERT INTO goods (goods_name, category, price, stock_quantity)
VALUES ('iPhone 14', 'Mobiles', 280000.00, 5);

INSERT INTO goods (goods_name, category, price, stock_quantity)
VALUES ('Office Chair', 'Furniture', 18000.00, 25);

INSERT INTO goods (goods_name, category, price, stock_quantity)
VALUES ('LED Monitor 24-inch', 'Electronics', 42000.00, 15);

INSERT INTO goods (goods_name, category, price, stock_quantity)
VALUES ('Laptop HP Pavilion', 'Electronics', 125000.00, 10);

INSERT INTO goods (goods_name, category, price, stock_quantity)
VALUES ('iPhone 14', 'Mobiles', 280000.00, 5);

INSERT INTO goods (goods_name, category, price, stock_quantity)
VALUES ('Office Chair', 'Furniture', 18000.00, 25);

INSERT INTO goods (goods_name, category, price, stock_quantity)
VALUES ('LED Monitor 24-inch', 'Electronics', 42000.00, 15);

INSERT INTO goods (goods_name, category, price, stock_quantity)
VALUES ('Bluetooth Headphones', 'Accessories', 8500.00, 40);

INSERT INTO goods (goods_name, category, price, stock_quantity)
VALUES ('Mechanical Keyboard', 'Accessories', 14500.00, 30);

INSERT INTO goods (goods_name, category, price, stock_quantity)
VALUES ('Samsung Galaxy S23', 'Mobiles', 260000.00, 8);

INSERT INTO goods (goods_name, category, price, stock_quantity)
VALUES ('Dell Inspiron Laptop', 'Electronics', 138000.00, 12);

INSERT INTO goods (goods_name, category, price, stock_quantity)
VALUES ('Wooden Study Table', 'Furniture', 29500.00, 18);

INSERT INTO goods (goods_name, category, price, stock_quantity)
VALUES ('Smartwatch Series 8', 'Wearables', 88000.00, 20);

INSERT INTO goods (goods_name, category, price, stock_quantity)
VALUES ('Gaming Mouse', 'Accessories', 6500.00, 50);

INSERT INTO goods (goods_name, category, price, stock_quantity)
VALUES ('Recliner Sofa', 'Furniture', 98000.00, 6);

INSERT INTO goods (goods_name, category, price, stock_quantity)
VALUES ('Power Bank 20000mAh', 'Accessories', 4200.00, 70);

INSERT INTO goods (goods_name, category, price, stock_quantity)
VALUES ('Wireless Earbuds', 'Accessories', 10500.00, 35);

INSERT INTO goods (goods_name, category, price, stock_quantity)
VALUES ('Tablet iPad Air', 'Mobiles', 145000.00, 9);

INSERT INTO goods (goods_name, category, price, stock_quantity)
VALUES ('Smart LED TV 55-inch', 'Electronics', 175000.00, 7);

INSERT INTO goods (goods_name, category, price, stock_quantity)
VALUES ('Bookshelf 5-Layer', 'Furniture', 15500.00, 22);

INSERT INTO goods (goods_name, category, price, stock_quantity)
VALUES ('External Hard Drive 1TB', 'Accessories', 11000.00, 25);

INSERT INTO goods (goods_name, category, price, stock_quantity)
VALUES ('Wireless Router', 'Electronics', 9500.00, 33);

INSERT INTO goods (goods_name, category, price, stock_quantity)
VALUES ('Office Desk Lamp', 'Furniture', 7200.00, 28);








