CREATE TABLE EMP(
emp_id INT CHECK (emp_id > 0),
emp_first VARCHAR2(45),
emp_last VARCHAR(45),
emp_age INT,

CONSTRAINT ch_age CHECK (emp_age > 17)
);

drop TABLE EMP;
desc EMP

-- Create the table
CREATE TABLE products (
    product_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_name VARCHAR2(100) NOT NULL,
    category VARCHAR2(50),
    price NUMBER(10,2),
    stock_quantity NUMBER,
    added_date DATE DEFAULT SYSDATE
    
    CONSTRAINT PK_PRODUCTS PRIMARY KEY (prduct_id)
);

ALTER TABLE products ADD CONSTRAINT PK_PRODUCTS PRIMARY KEY (prduct_id);



ALTER TABLE PRoduction ADD productsssss VARCHAR2(45);


ALTER TABLE Products RENAME TO PRoduction;
ALTER TABLE production RENAME COLUMN productsssss TO products;

select * from production;




-- Insert sample data
INSERT INTO products (product_name, category, price, stock_quantity)
VALUES ('Laptop HP Pavilion', 'Electronics', 125000.00, 10);

INSERT INTO products (product_name, category, price, stock_quantity)
VALUES ('iPhone 14', 'Mobiles', 280000.00, 5);

INSERT INTO products (product_name, category, price, stock_quantity)
VALUES ('Office Chair', 'Furniture', 18000.00, 25);

INSERT INTO products (product_name, category, price, stock_quantity)
VALUES ('LED Monitor 24-inch', 'Electronics', 42000.00, 15);

-- View all records
SELECT * FROM products;

INSERT INTO products (product_name, category, price, stock_quantity)
VALUES ('Laptop HP Pavilion', 'Electronics', 125000.00, 10);

INSERT INTO products (product_name, category, price, stock_quantity)
VALUES ('iPhone 14', 'Mobiles', 280000.00, 5);

INSERT INTO products (product_name, category, price, stock_quantity)
VALUES ('Office Chair', 'Furniture', 18000.00, 25);

INSERT INTO products (product_name, category, price, stock_quantity)
VALUES ('LED Monitor 24-inch', 'Electronics', 42000.00, 15);

INSERT INTO products (product_name, category, price, stock_quantity)
VALUES ('Bluetooth Headphones', 'Accessories', 8500.00, 40);

INSERT INTO products (product_name, category, price, stock_quantity)
VALUES ('Mechanical Keyboard', 'Accessories', 14500.00, 30);

INSERT INTO products (product_name, category, price, stock_quantity)
VALUES ('Samsung Galaxy S23', 'Mobiles', 260000.00, 8);

INSERT INTO products (product_name, category, price, stock_quantity)
VALUES ('Dell Inspiron Laptop', 'Electronics', 138000.00, 12);

INSERT INTO products (product_name, category, price, stock_quantity)
VALUES ('Wooden Study Table', 'Furniture', 29500.00, 18);

INSERT INTO products (product_name, category, price, stock_quantity)
VALUES ('Smartwatch Series 8', 'Wearables', 88000.00, 20);

INSERT INTO products (product_name, category, price, stock_quantity)
VALUES ('Gaming Mouse', 'Accessories', 6500.00, 50);

INSERT INTO products (product_name, category, price, stock_quantity)
VALUES ('Recliner Sofa', 'Furniture', 98000.00, 6);

INSERT INTO products (product_name, category, price, stock_quantity)
VALUES ('Power Bank 20000mAh', 'Accessories', 4200.00, 70);

INSERT INTO products (product_name, category, price, stock_quantity)
VALUES ('Wireless Earbuds', 'Accessories', 10500.00, 35);

INSERT INTO products (product_name, category, price, stock_quantity)
VALUES ('Tablet iPad Air', 'Mobiles', 145000.00, 9);

INSERT INTO products (product_name, category, price, stock_quantity)
VALUES ('Smart LED TV 55-inch', 'Electronics', 175000.00, 7);

INSERT INTO products (product_name, category, price, stock_quantity)
VALUES ('Bookshelf 5-Layer', 'Furniture', 15500.00, 22);

INSERT INTO products (product_name, category, price, stock_quantity)
VALUES ('External Hard Drive 1TB', 'Accessories', 11000.00, 25);

INSERT INTO products (product_name, category, price, stock_quantity)
VALUES ('Wireless Router', 'Electronics', 9500.00, 33);

INSERT INTO products (product_name, category, price, stock_quantity)
VALUES ('Office Desk Lamp', 'Furniture', 7200.00, 28);

SELECT * FROM PRODUCTS;



------------------SELECT CLAUSE----------------------------------------


SELECT DISTINCT Stock_Quantity,Product_name, product_id FROM Products;  --SQL looks at the combination of two

SELECT DISTINCT Stock_Quantity,Product_name, product_id FROM PRODUCTS; --SQL looks at the combination of three



----------------------------------------WHERE CLAUSE---------------------------

SELECT DISTINCT Stock_quantity, Product_name FROM Products
WHERE Product_ID > 10;
SELECT DISTINCT Stock_Quantity FROM PRODUCTS;

SELECT DISTINCT Stock_quantity, Product_name FROM Products
WHERE Product_ID IN (1,30,31,32,33,34);

SELECT DISTINCT Stock_quantity, Product_name FROM Products
WHERE Product_ID BETWEEN 10 AND 90;

SELECT DISTINCT Stock_quantity, Product_name FROM Products
WHERE product_name LIKE 'L%' ;

SELECT DISTINCT Stock_quantity, Product_name FROM Products
WHERE (product_name LIKE 'L%' OR Product_ID BETWEEN 10 AND 90) AND price >300;

SELECT DISTINCT Stock_quantity, Product_name FROM Products
WHERE product_name = 'Wireless Router' OR Stock_quantity = 33;

SELECT product_name FROM products
WHERE stock_quantity NOT BETWEEN 33 AND 50;

-------------------ORDER BY------------------

SELECT DISTINCT Stock_quantity, Product_name FROM Products
WHERE Product_ID BETWEEN 10 AND 90;

SELECT product_name FROM products
ORDER BY product_id ASC;


------------------------------------INSERT INTO---------------------------------

INSERT INTO Products ('PRODUCT_ID','PRODUCT_NAME','CATEGORY','PRICE','STOCK_QUAUTITY')
--(33, 'HP Elitebook 1250','Laptop', '30000','43' )
VALUES
(34, 'HP Elitebook 1250','Electronics', '30000','43' );



-----------------------Update--------------------

UPDATE products
SET PRODUCT_NAME = 'CHANGED', PRICE = 90000
WHERE product_id IN (4,5,6);



------------------DELETE-------------------
DELETE FROM Products WHERE Stock_Quantity = 25;


----------------DEFAULT----------------
CREATE TABLE orders (
    o_id         INT NOT NULL,
    order_number INT NOT NULL,
    order_name   VARCHAR(45)
    --order_date   DATE DEFAULT getdate()
);

CREATE TABLE Persons (
    ID int NOT NULL,
    LastName varchar(255) NOT NULL,
    FirstName varchar(255),
    Age int DEFAULT 18,
    City varchar(255) DEFAULT 'Sandnes'
);

INSERT INTO products (product_name, category, price, stock_quantity)
VALUES ('iPhone 14', 'Mobiles', 280000.00, 10);

select * from products;

--ALTER TABLE Production RENAME TO Products;
