----------------------Extended Excercise on Joins, Comparision Operators, Logical Operators and Merges.
---------------------------------------------DDL------------------------------
CREATE TABLE EMPLOYEEES(
E_id NUMBER(9) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
E_first VARCHAR(35) NOT NULL,
E_last VARCHAR(35),
Age INT,
Gender CHAR(6),
Dept_id NUMBER(9),
Mgr_id NUMBER(9),
Salary NUMBER,
Joining_date date,
Leaving_date date
);


CREATE TABLE DEPARTMEENTS(
Dept_id NUMBER(9) GENERATED BY DEFAULT AS IDENTITY(START WITH 50 INCREMENT BY 1) PRIMARY KEY,
Dept_Name VARCHAR(35) NOT NULL
);


CREATE TABLE MANAGEERS(
Mgr_id NUMBER(9) GENERATED BY DEFAULT AS IDENTITY(START WITH 100 INCREMENT BY 1) PRIMARY KEY,
Mgr_first VARCHAR(35),
Mgr_last VARCHAR(35),
dept_id NUMBER(35),
Age INT,
Gender CHAR(6),
Salary NUMBER,
Joining_date date,
Leaving_date date
);



ALTER TABLE EMPLOYEEES ADD CONSTRAINT fk_employeees_departments_deptID 
FOREIGN KEY (dept_id) REFERENCES DEPARTMEENTS (dept_id);

ALTER TABLE EMPLOYEEES ADD CONSTRAINT fk_employeees_manageers_mgrID
FOREIGN KEY (mgr_id) REFERENCES MANAGEERS (mgr_id);

ALTER TABLE MANAGEERS ADD CONSTRAINT fk_manageers_departmeents_deptID
FOREIGN KEY (dept_id) REFERENCES DEPARTMEENTS (dept_id);


--ALTER TABLE EMPLOYEEES ADD CONSTRAINT chk_null_emp_Jdate
--ADD CHECK (Joining_date IS NOT NULL);

ALTER TABLE EMPLOYEEES 
MODIFY Joining_date date NOT NULL;

ALTER TABLE MANAGEERS
MODIFY Joining_date date NOT NULL;

ALTER TABLE EMPLOYEEES ADD CONSTRAINT chk_age_employeees
CHECK (Age > 18);

ALTER TABLE MANAGEERS ADD CONSTRAINT chk_age_manageers
CHECK (Age > 18);

ALTER TABLE EMPLOYEEES ADD CONSTRAINT chk_gender_employeees
CHECK (Gender IN ('Male', 'Female'));

ALTER TABLE MANAGEERS ADD CONSTRAINT chk_gender_manageers
CHECK (Gender IN ('Male','Female'));

ALTER TABLE MANAGEERS MODIFY 
Salary DEFAULT 25000;

ALTER TABLE MANAGEERS MODIFY 
Salary NOT NULL;

info MANAGEERS;
info EMPLOYEEES;
info DEPARTMEENTS;

-----------------------------------------------DML-----------------------------------------
-------------------------------------------Inserting data ---------------------------------
INSERT INTO DEPARTMENTS(dept_name)
VALUES('HR');

INSERT INTO DEPARTMEENTS(dept_name)
VALUES('Sales');

INSERT INTO DEPARTMEENTS(dept_name)
VALUES('IT');

INSERT INTO DEPARTMEENTS(dept_name)
VALUES('Marketing');

INSERT INTO DEPARTMEENTS(dept_name)
VALUES('Accounting');

INSERT INTO DEPARTMEENTS(dept_name)
VALUES('Management');

INSERT INTO DEPARTMEENTS(dept_name)
VALUES('QEC');

INSERT INTO DEPARTMEENTS(dept_name)
VALUES('Contacts');

INSERT INTO DEPARTMEENTS(dept_name)
VALUES('Finance');

INSERT INTO DEPARTMEENTS(dept_name)
VALUES('Administration');

SELECT * FROM MANAGEERS;
SELECT * FROM DEPARTMEENTS;



INSERT INTO MANAGEERS(Mgr_first, mgr_last, dept_id, age, gender, salary, joining_date, leaving_date)
VALUES('Rasheed', 'Latif', 52, 45, 'Male', 70000, TO_DATE('16-10-2008', 'DD-MM-YYYY'), TO_DATE('14-10-2010', 'DD-MM-YYYY'));

INSERT INTO MANAGEERS(Mgr_first, mgr_last, dept_id, age, gender, salary, joining_date, leaving_date)
VALUES('Saqib', 'Nizam', 50, 53, 'Male', 90000, TO_DATE('19-12-2010', 'DD-MM-YYYY'), TO_DATE('22-02-2012', 'DD-MM-YYYY'));

INSERT INTO MANAGEERS(Mgr_first, mgr_last, dept_id, age, gender, salary, joining_date, leaving_date)
VALUES('Baber', 'Ali', 57, 63, 'Male', 120000, TO_DATE('09-02-2011', 'DD-MM-YYYY'), null);


INSERT INTO MANAGEERS(Mgr_first, mgr_last, dept_id, age, gender, salary, joining_date, leaving_date)
VALUES('Sadia', 'Khan', 50, 45, 'Female', 95000, TO_DATE('15-03-2012', 'DD-MM-YYYY'), NULL);

INSERT INTO MANAGEERS(Mgr_first, mgr_last, dept_id, age, gender, salary, joining_date, leaving_date)
VALUES('Asim', 'Raza', 51, 52, 'Male', 120000, TO_DATE('20-07-2009', 'DD-MM-YYYY'), NULL);

INSERT INTO MANAGEERS(Mgr_first, mgr_last, dept_id, age, gender, salary, joining_date, leaving_date)
VALUES('Hira', 'Malik', 52, 39, 'Female', 88000, TO_DATE('11-01-2015', 'DD-MM-YYYY'), NULL);

INSERT INTO MANAGEERS(Mgr_first, mgr_last, dept_id, age, gender, salary, joining_date, leaving_date)
VALUES('Tariq', 'Javed', 53, 61, 'Male', 132000, TO_DATE('05-11-2008', 'DD-MM-YYYY'), TO_DATE('15-05-2022', 'DD-MM-YYYY'));

INSERT INTO MANAGEERS(Mgr_first, mgr_last, dept_id, age, gender, salary, joining_date, leaving_date)
VALUES('Maria', 'Shahid', 54, 42, 'Female', 97000, TO_DATE('17-06-2014', 'DD-MM-YYYY'), NULL);

INSERT INTO MANAGEERS(Mgr_first, mgr_last, dept_id, age, gender, salary, joining_date, leaving_date)
VALUES('Imran', 'Naeem', 55, 48, 'Male', 102000, TO_DATE('03-09-2011', 'DD-MM-YYYY'), NULL);

INSERT INTO MANAGEERS(Mgr_first, mgr_last, dept_id, age, gender, salary, joining_date, leaving_date)
VALUES('Ayesha', 'Rafiq', 56, 37, 'Female', 89000, TO_DATE('22-08-2016', 'DD-MM-YYYY'), NULL);

INSERT INTO MANAGEERS(Mgr_first, mgr_last, dept_id, age, gender, salary, joining_date, leaving_date)
VALUES('Noman', 'Iqbal', 58, 55, 'Male', 118000, TO_DATE('09-04-2010', 'DD-MM-YYYY'), NULL);




INSERT INTO MANAGEERS(Mgr_first, mgr_last, dept_id, age, gender, salary, joining_date, leaving_date)
VALUES('Baber', 'Ali', 57, 59, 'Male', 110000, TO_DATE('09-02-2010', 'DD-MM-YYYY'), NULL);

INSERT INTO MANAGEERS(Mgr_first, mgr_last, dept_id, age, gender, salary, joining_date, leaving_date)
VALUES('Sadia', 'Khan', 50, 45, 'Female', 95000, TO_DATE('15-03-2012', 'DD-MM-YYYY'), NULL);

INSERT INTO MANAGEERS(Mgr_first, mgr_last, dept_id, age, gender, salary, joining_date, leaving_date)
VALUES('Asim', 'Raza', 51, 52, 'Male', 120000, TO_DATE('20-07-2009', 'DD-MM-YYYY'), NULL);

INSERT INTO MANAGEERS(Mgr_first, mgr_last, dept_id, age, gender, salary, joining_date, leaving_date)
VALUES('Hira', 'Malik', 52, 39, 'Female', 88000, TO_DATE('11-01-2015', 'DD-MM-YYYY'), NULL);

INSERT INTO MANAGEERS(Mgr_first, mgr_last, dept_id, age, gender, salary, joining_date, leaving_date)
VALUES('Tariq', 'Javed', 53, 61, 'Male', 132000, TO_DATE('05-11-2008', 'DD-MM-YYYY'), TO_DATE('15-05-2022', 'DD-MM-YYYY'));

INSERT INTO MANAGEERS(Mgr_first, mgr_last, dept_id, age, gender, salary, joining_date, leaving_date)
VALUES('Maria', 'Shahid', 54, 42, 'Female', 97000, TO_DATE('17-06-2014', 'DD-MM-YYYY'), NULL);

INSERT INTO MANAGEERS(Mgr_first, mgr_last, dept_id, age, gender, salary, joining_date, leaving_date)
VALUES('Imran', 'Naeem', 55, 48, 'Male', 102000, TO_DATE('03-09-2011', 'DD-MM-YYYY'), NULL);

INSERT INTO MANAGEERS(Mgr_first, mgr_last, dept_id, age, gender, salary, joining_date, leaving_date)
VALUES('Ayesha', 'Rafiq', 56, 37, 'Female', 89000, TO_DATE('22-08-2016', 'DD-MM-YYYY'), NULL);

INSERT INTO MANAGEERS(Mgr_first, mgr_last, dept_id, age, gender, salary, joining_date, leaving_date)
VALUES('Noman', 'Iqbal', 58, 55, 'Male', 118000, TO_DATE('09-04-2010', 'DD-MM-YYYY'), NULL);

INSERT INTO MANAGEERS(Mgr_first, mgr_last, dept_id, age, gender, salary, joining_date, leaving_date)
VALUES('Faisal', 'Mehmood', 50, 46, 'Male', 101000, TO_DATE('10-02-2013', 'DD-MM-YYYY'), NULL);

INSERT INTO MANAGEERS(Mgr_first, mgr_last, dept_id, age, gender, salary, joining_date, leaving_date)
VALUES('Nida', 'Akhtar', 51, 34, 'Female', 87000, TO_DATE('14-10-2017', 'DD-MM-YYYY'), NULL);

INSERT INTO MANAGEERS(Mgr_first, mgr_last, dept_id, age, gender, salary, joining_date, leaving_date)
VALUES('Kamran', 'Ahmed', 52, 50, 'Male', 111000, TO_DATE('05-05-2011', 'DD-MM-YYYY'), NULL);

INSERT INTO MANAGEERS(Mgr_first, mgr_last, dept_id, age, gender, salary, joining_date, leaving_date)
VALUES('Rimsha', 'Saeed', 53, 41, 'Female', 94000, TO_DATE('22-12-2015', 'DD-MM-YYYY'), NULL);

INSERT INTO MANAGEERS(Mgr_first, mgr_last, dept_id, age, gender, salary, joining_date, leaving_date)
VALUES('Adnan', 'Qureshi', 54, 58, 'Male', 126000, TO_DATE('30-07-2007', 'DD-MM-YYYY'), TO_DATE('18-03-2021', 'DD-MM-YYYY'));

INSERT INTO MANAGEERS(Mgr_first, mgr_last, dept_id, age, gender, salary, joining_date, leaving_date)
VALUES('Lubna', 'Farooq', 55, 44, 'Female', 93000, TO_DATE('08-06-2014', 'DD-MM-YYYY'), NULL);

INSERT INTO MANAGEERS(Mgr_first, mgr_last, dept_id, age, gender, salary, joining_date, leaving_date)
VALUES('Hassan', 'Rafiq', 56, 53, 'Male', 117000, TO_DATE('16-01-2010', 'DD-MM-YYYY'), NULL);

INSERT INTO MANAGEERS(Mgr_first, mgr_last, dept_id, age, gender, salary, joining_date, leaving_date)
VALUES('Rania', 'Sheikh', 57, 36, 'Female', 86000, TO_DATE('03-09-2018', 'DD-MM-YYYY'), NULL);

INSERT INTO MANAGEERS(Mgr_first, mgr_last, dept_id, age, gender, salary, joining_date, leaving_date)
VALUES('Zafar', 'Abbas', 58, 60, 'Male', 128000, TO_DATE('21-05-2006', 'DD-MM-YYYY'), TO_DATE('30-12-2020', 'DD-MM-YYYY'));

INSERT INTO MANAGEERS(Mgr_first, mgr_last, dept_id, age, gender, salary, joining_date, leaving_date)
VALUES('Mehwish', 'Iqbal', 53, 39, 'Female', 91000, TO_DATE('12-04-2016', 'DD-MM-YYYY'), NULL);

INSERT INTO MANAGEERS(Mgr_first, mgr_last, dept_id, age, gender, salary, joining_date, leaving_date)
VALUES('Rashid', 'Anwar', 52, 49, 'Male', 106000, TO_DATE('09-10-2011', 'DD-MM-YYYY'), NULL);



SELECT * FROM EMPLOYEEES;

INSERT INTO EMPLOYEEES(E_first, E_Last, Age, Gender, dept_id, mgr_id, salary, joining_date, leaving_date)
VALUES('Adeel', 'Khan', 26, 'Male', 50, 101, 65000, TO_DATE('15-03-2020', 'DD-MM-YYYY'), NULL);

INSERT INTO EMPLOYEEES(E_first, E_Last, Age, Gender, dept_id, mgr_id, salary, joining_date, leaving_date)
VALUES('Sana', 'Ahmed', 29, 'Female', 51, 107, 72000, TO_DATE('11-07-2019', 'DD-MM-YYYY'), NULL);

INSERT INTO EMPLOYEEES(E_first, E_Last, Age, Gender, dept_id, mgr_id, salary, joining_date, leaving_date)
VALUES('Rizwan', 'Malik', 33, 'Male', 52, 109, 78000, TO_DATE('25-01-2018', 'DD-MM-YYYY'), NULL);

INSERT INTO EMPLOYEEES(E_first, E_Last, Age, Gender, dept_id, mgr_id, salary, joining_date, leaving_date)
VALUES('Iqra', 'Naseer', 27, 'Female', 53, 111, 68000, TO_DATE('05-06-2021', 'DD-MM-YYYY'), NULL);

INSERT INTO EMPLOYEEES(E_first, E_Last, Age, Gender, dept_id, mgr_id, salary, joining_date, leaving_date)
VALUES('Bilal', 'Rafiq', 31, 'Male', 54, 115, 76000, TO_DATE('17-02-2017', 'DD-MM-YYYY'), TO_DATE('12-09-2023', 'DD-MM-YYYY'));

INSERT INTO EMPLOYEEES(E_first, E_Last, Age, Gender, dept_id, mgr_id, salary, joining_date, leaving_date)
VALUES('Hina', 'Qureshi', 25, 'Female', 55, 108, 64000, TO_DATE('20-04-2022', 'DD-MM-YYYY'), NULL);

INSERT INTO EMPLOYEEES(E_first, E_Last, Age, Gender, dept_id, mgr_id, salary, joining_date, leaving_date)
VALUES('Zeeshan', 'Ali', 30, 'Male', 56, 117, 81000, TO_DATE('12-10-2016', 'DD-MM-YYYY'), NULL);

INSERT INTO EMPLOYEEES(E_first, E_Last, Age, Gender, dept_id, mgr_id, salary, joining_date, leaving_date)
VALUES('Maria', 'Javed', 28, 'Female', 57, 113, 70000, TO_DATE('09-08-2020', 'DD-MM-YYYY'), NULL);

INSERT INTO EMPLOYEEES(E_first, E_Last, Age, Gender, dept_id, mgr_id, salary, joining_date, leaving_date)
VALUES('Omer', 'Khalid', 35, 'Male', 58, 119, 88000, TO_DATE('03-05-2015', 'DD-MM-YYYY'), NULL);

INSERT INTO EMPLOYEEES(E_first, E_Last, Age, Gender, dept_id, mgr_id, salary, joining_date, leaving_date)
VALUES('Laiba', 'Rehman', 24, 'Female', 50, 105, 60000, TO_DATE('18-02-2023', 'DD-MM-YYYY'), NULL);

INSERT INTO EMPLOYEEES(E_first, E_Last, Age, Gender, dept_id, mgr_id, salary, joining_date, leaving_date)
VALUES('Shahzaib', 'Anwar', 32, 'Male', 51, 112, 75000, TO_DATE('30-09-2018', 'DD-MM-YYYY'), NULL);

INSERT INTO EMPLOYEEES(E_first, E_Last, Age, Gender, dept_id, mgr_id, salary, joining_date, leaving_date)
VALUES('Erum', 'Yousaf', 29, 'Female', 52, 116, 71000, TO_DATE('10-03-2019', 'DD-MM-YYYY'), NULL);

INSERT INTO EMPLOYEEES(E_first, E_Last, Age, Gender, dept_id, mgr_id, salary, joining_date, leaving_date)
VALUES('Ali', 'Raza', 27, 'Male', 53, 118, 69000, TO_DATE('05-11-2021', 'DD-MM-YYYY'), NULL);

INSERT INTO EMPLOYEEES(E_first, E_Last, Age, Gender, dept_id, mgr_id, salary, joining_date, leaving_date)
VALUES('Mehak', 'Hassan', 31, 'Female', 54, 106, 74000, TO_DATE('08-01-2018', 'DD-MM-YYYY'), NULL);

INSERT INTO EMPLOYEEES(E_first, E_Last, Age, Gender, dept_id, mgr_id, salary, joining_date, leaving_date)
VALUES('Usman', 'Farid', 34, 'Male', 55, 110, 79000, TO_DATE('14-07-2016', 'DD-MM-YYYY'), TO_DATE('22-04-2022', 'DD-MM-YYYY'));

INSERT INTO EMPLOYEEES(E_first, E_Last, Age, Gender, dept_id, mgr_id, salary, joining_date, leaving_date)
VALUES('Rimsha', 'Khalil', 26, 'Female', 56, 114, 66000, TO_DATE('21-09-2020', 'DD-MM-YYYY'), NULL);

INSERT INTO EMPLOYEEES(E_first, E_Last, Age, Gender, dept_id, mgr_id, salary, joining_date, leaving_date)
VALUES('Hassan', 'Tariq', 29, 'Male', 57, 111, 72000, TO_DATE('19-05-2019', 'DD-MM-YYYY'), NULL);

INSERT INTO EMPLOYEEES(E_first, E_Last, Age, Gender, dept_id, mgr_id, salary, joining_date, leaving_date)
VALUES('Maira', 'Zahid', 25, 'Female', 58, 115, 63000, TO_DATE('02-03-2022', 'DD-MM-YYYY'), NULL);

INSERT INTO EMPLOYEEES(E_first, E_Last, Age, Gender, dept_id, mgr_id, salary, joining_date, leaving_date)
VALUES('Nabeel', 'Haider', 33, 'Male', 50, 109, 78000, TO_DATE('09-12-2017', 'DD-MM-YYYY'), NULL);

INSERT INTO EMPLOYEEES(E_first, E_Last, Age, Gender, dept_id, mgr_id, salary, joining_date, leaving_date)
VALUES('Anum', 'Iqbal', 30, 'Female', 51, 117, 71000, TO_DATE('27-08-2018', 'DD-MM-YYYY'), NULL);

SELECT * FROM EMPLOYEEES;


------------------------------------UPDATING AND DELETING DATA-----------------------------------------
UPDATE EMPLOYEEES
SET Salary = Salary + 4000
WHERE (Salary < 70000);


DELETE FROM EMPLOYEEES
WHERE (SALARY < 20000) AND (E_id > 2);

------------------------------------MERGING DATA-------------------------------------------------------
CREATE TABLE Employeees_updated AS
(SELECT * FROM EMPLOYEEES);


SELECT * FROM Employeees_updated;

UPDATE Employeees_updated
SET SALARY = SALARY + 5000, Age = Age + 2;


MERGE INTO EMPLOYEEES T
USING EMPLOYEEES_UPDATED S
ON (S.E_id = T.E_id)

WHEN MATCHED THEN
UPDATE SET
T.SALARY = S.SALARY

WHEN NOT MATCHED THEN
INSERT(E_first, E_Last, Age, Gender, dept_id, mgr_id, salary, joining_date, leaving_date)
VALUES(S.E_first, S.E_Last, S.Age, S.Gender, S.dept_id, S.mgr_id, S.salary, S.joining_date, S.leaving_date); 


-----------------------------------------JOINSSSSS-------------------------------------------
----------------------------------------NATURAL JOIN-----------------------------------------
SELECT * FROM EMPLOYEEES;
SELECT * FROM DEPARTMEENTS;
ALTER TABLE DEPARTMEENTS ADD COLUMN E_FIRST 
SELECT * FROM MANAGEERS;

SELECT E_ID, E_FIRST, E_LAST, GENDER, DEPT_ID, DEPT_NAME 
FROM EMPLOYEEES 
NATURAL JOIN DEPARTMEENTS
WHERE GENDER = 'Female'
ORDER BY E_First;

SELECT E.E_ID, E.E_FIRST, E.E_LAST, E.GENDER, M.MGR_ID, M.MGR_FIRST, M.MGR_LAST FROM EMPLOYEEES E
INNER JOIN MANAGEERS M
ON (E.MGR_ID = M.MGR_ID);


SELECT * FROM EMPLOYEEES S
JOIN EMPLOYEEES T
ON (S.E_ID = T.E_ID);
WHERE ;

----------------------------------------SET Operations--------------------------------------
CREATE TABLE MANAGEERS_UPDATED AS (
SELECT * FROM MANAGEERS
WHERE MGR_ID > 110);

UPDATE MANAGEERS_UPDATED2K   ------------------Increased Salary by 2000 for all rows.
SET Salary = Salary + 2000;

CREATE TABLE MANAGEERS_UPDATED2K AS
(SELECT * FROM MANAGEERS_UPDATED);

SELECT * FROM MANAGEERS
UNION
SELECT * FROM MANAGEERS_UPDATED;

SELECT * FROM MANAGEERS_UPDATED2k
UNION
SELECT * FROM MANAGEERS;













