SELECT * FROM EMPLOYEEES;
SELECT * FROM PROJECTS;
SELECT * FROM MANAGEERS;
SELECT * FROM DEPARTMEENTS;


SELECT COUNT(mgr_first) FROM MANAGEERS;
SELECT COUNT(*) FROM MANAGEERS;

SELECT MAX(joining_date), MIN(AGE), MIN(leaving_date), AVG(Salary) FROM MANAGEERS;
SELECT SUM(SALARY)/COUNT(SALARY) AS AVERAGE_SALARY FROM MANAGEERS;

