CREATE TABLE Employees(
E_id NUMBER(9) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
E_first VARCHAR2(30),
E_last VARCHAR2(30),
E_Age INT,
E_Gender Char(6),
E_Salary NUMBER(9)
);

drop table employees;

DROP TABLE Employees;
DROP TABLE Employees_UP;

CREATE TABLE Employees_UP(
E_id NUMBER(9) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
E_first VARCHAR2(30),
E_last VARCHAR2(30),
E_Age INT,
E_Gender Char(6),
E_Salary NUMBER(9)
);

INSERT INTO Employees(E_first, E_last, E_Age, E_Gender, E_Salary)
VALUES ('James', 'Rodriguz', 45, 'Male', 60000);

INSERT INTO Employees(E_first, E_last, E_Age, E_Gender, E_Salary)
VALUES ('Selena', 'Gomez', 35, 'Female', 90000);

INSERT INTO Employees(E_first, E_last, E_Age, E_Gender, E_Salary)
VALUES ('Roberto', 'Carlos', 55, 'Male', 120000);

INSERT INTO Employees(E_first, E_last, E_Age, E_Gender, E_Salary)
VALUES ('Luka', 'Modric', 39, 'Male', 780000);

INSERT INTO Employees(E_first, E_last, E_Age, E_Gender, E_Salary)
VALUES ('Amilia', 'Clark', 38, 'Female', 82000);

INSERT INTO Employees(E_first, E_last, E_Age, E_Gender, E_Salary)
VALUES ('Alex', 'Sanches', 43, 'Male', 910000);




INSERT INTO Employees_UP(E_first, E_last, E_Age, E_Gender, E_Salary)
VALUES ('James', 'Rodriguz', 46, 'Male', 62000);

INSERT INTO Employees_UP(E_first, E_last, E_Age, E_Gender, E_Salary)
VALUES ('Selena', 'Gomez', 47, 'Female', 95000);

INSERT INTO Employees_UP(E_first, E_last, E_Age, E_Gender, E_Salary)
VALUES ('Roberto', 'Carlos', 58, 'Male', 130000);

INSERT INTO Employees_UP(E_first, E_last, E_Age, E_Gender, E_Salary)
VALUES ('Luka', 'Modric', 42, 'Male', 78000);

INSERT INTO Employees_UP(E_first, E_last, E_Age, E_Gender, E_Salary)
VALUES ('Amilia', 'Clark', 38, 'Female', 82000);

INSERT INTO Employees_UP(E_first, E_last, E_Age, E_Gender, E_Salary)
VALUES ('Cristiano', 'Ronaldo', 40, 'Male', 1500000);


SELECT * FROM Employees;
SELECT * FROM Employees_UP;


MERGE INTO Employees T
USING Employees_UP S
ON (S.E_First = T.E_First AND S.E_Last = T.E_Last)

WHEN MATCHED THEN
UPDATE SET T.E_Age = S.E_Age, T.E_Salary = S.E_Salary
    
WHEN NOT MATCHED THEN
INSERT (E_first, E_last, E_Age, E_Gender, E_Salary)
VALUES(S.E_first, S.E_last, S.E_Age, S.E_Gender, S.E_Salary);



MERGE INTO Employees T
USING Employees_UP S
ON (T.E_ID = S.E_ID)

WHEN MATCHED THEN
UPDATE SET T.E_salary = S.E_salary

WHEN NOT MATCHED THEN
INSERT (E_first, E_last, E_age, E_gender, E_salary)
values(s.E_first, s.E_last, s.E_age, s.E_gender, s.E_salary);

SELECT * FROM Employees_UP
ORDER BY E_SALARY DESC
OFFSET 0 ROWS
FETCH NEXT 3 ROWS WITH TIES;

SELECT * FROM EMPLOYEES_UP
ORDER BY E_salary DESC,E_age ASC
OFFSET 2 ROWS
FETCH NEXT 3 ROWS ONLY;

