--Create utility package to have three different procedures in it;
----All the variables should be public.
----One procedure should output the second highest salary and emp_id of the department given.
----One function to return Y/N if the salary of the employee is greater than the average salary of all the employees of his/her
----department.
----One Procedure to log the logs entry.
----Third procedure should update the department_id of the second highest employee of the department of the given employee to input
----department id.
----Call the first procedure and second procedure in it to fetch the employee/department details and log it in the logs table as per
----convinience 
----Call different procedures of the package in anonymous block and try to use the intialization method and access the variable.


CREATE OR REPLACE PACKAGE PKG_UTIL
AS
    emp_count NUMBER;
    v_sal EMPLOYEES_FAIZAN.salary%type;
    v_emp EMPLOYEES_FAIZAN.employee_id%type;
    func_count PLS_INTEGER; 
    lg_count NUMBER;
    p_dept_cnt NUMBER;
    p_emp_cnt NUMBER;
    func_emp_dept EMPLOYEES_FAIZAN.DEPARTMENT_ID%TYPE;
    
    PROCEDURE proc_out_emp (
    dept_id IN employees_faizan.department_id%TYPE,
    emp_out OUT employees_faizan.employee_id%TYPE,
    sal_out OUT employees_faizan.salary%TYPE,
    v_state OUT VARCHAR2
    );

    FUNCTION func_hsal (
        emp_id_in IN employees_faizan.employee_id%TYPE
    ) RETURN VARCHAR2;
    
    PROCEDURE proc_logs (
        log_msg IN VARCHAR2
    );
    
    PROCEDURE proc_upt_emp (
        emp_id_in IN employees_faizan.employee_id%TYPE,
        dept_id_in IN employees_faizan.department_id%TYPE,
        v_state OUT VARCHAR2
    );
        
END PKG_UTIL;
/

CREATE OR REPLACE PACKAGE BODY PKG_UTIL
AS
    PROCEDURE proc_out_emp (
    dept_id IN employees_faizan.department_id%TYPE,
    emp_out OUT employees_faizan.employee_id%TYPE,
    sal_out OUT employees_faizan.salary%TYPE,
    v_state OUT VARCHAR2) 
    AS 
    BEGIN
        v_state := 0;
        SELECT COUNT(*) INTO emp_count FROM EMPLOYEES_FAIZAN
        WHERE DEPARTMENT_ID = dept_id;
        
        IF emp_count < 2 THEN
            v_state := 'Not Enough Employees';
            RETURN;
        ELSE
            SELECT EMPLOYEE_ID, SALARY INTO emp_out, sal_out FROM EMPLOYEES_FAIZAN
            WHERE DEPARTMENT_ID = dept_id
            ORDER BY SALARY DESC
            OFFSET 1 ROWS
            FETCH NEXT 1 ROWS ONLY;
            
            proc_logs('Procedure 1 was executed');
            
        END IF;
    END proc_out_emp;
        
        FUNCTION func_hsal (
        emp_id_in IN employees_faizan.employee_id%TYPE
        ) RETURN VARCHAR2
        IS
        BEGIN
            SELECT DEPARTMENT_ID INTO func_emp_dept FROM EMPLOYEES_FAIZAN
            WHERE EMPLOYEE_ID = emp_id_in;
            
            SELECT COUNT(*) INTO func_count FROM EMPLOYEES_FAIZAN
            WHERE SALARY > (SELECT AVG(SALARY) FROM EMPLOYEES_FAIZAN
            WHERE DEPARTMENT_ID = func_emp_dept) AND
            EMPLOYEE_ID = emp_id_in;
            

            IF func_count > 0 THEN
                RETURN 'Y';
            ELSE
                RETURN 'N';
            END IF;
         END func_hsal;
        
        PROCEDURE proc_logs (
        log_msg IN VARCHAR2
        )
        AS
        BEGIN
        SELECT COUNT(*) INTO lg_count FROM ALL_TABLES
        WHERE TABLE_NAME = 'LOGS_TAB';        
        
        IF lg_count = 0 THEN
            EXECUTE IMMEDIATE 'CREATE TABLE logs_tab
            (log_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            log_ts TIMESTAMP DEFAULT SYSTIMESTAMP,
            log_message VARCHAR2(200)
            )';
        END IF;
        
        EXECUTE IMMEDIATE 'INSERT INTO logs_tab(log_message) VALUES (:1)' 
        USING log_msg;
            
        DBMS_OUTPUT.PUT_LINE('log updated');
    END;
    
        PROCEDURE proc_upt_emp (
        emp_id_in IN employees_faizan.employee_id%TYPE,
        dept_id_in IN employees_faizan.department_id%TYPE,
        v_state OUT VARCHAR2
        ) 
        AS
        BEGIN
        SELECT COUNT(*) INTO p_emp_cnt FROM EMPLOYEES_FAIZAN
        WHERE EMPLOYEE_ID = emp_id_in;
        
        SELECT COUNT(*) INTO p_dept_cnt FROM EMPLOYEES_FAIZAN
        WHERE DEPARTMENT_ID = dept_id_in;
        
        IF p_emp_cnt > 0 AND p_dept_cnt > 0 THEN
            UPDATE EMPLOYEES_FAIZAN
            SET DEPARTMENT_ID = dept_id_in
            WHERE employee_id = emp_id_in;
            v_state := 'Employee record updated successfully';
        ELSE
            v_state := 'Either Employee or Department does not exist';
            RETURN;
        END IF;
    END proc_upt_emp;
END PKG_UTIL;
/        
        
SELECT * FROM ALL_TABLES
WHERE TABLE_NAME = 'LOGS_TAB';

SELECT * FROM EMPLOYEES_FAIZAN;
SELECT * FROM DEPARTMENTSS;



BEGIN
    
    DBMS_OUTPUT.PUT_LINE(PKG_UTIL.func_hsal(1003));
   
END;
/
proc_logs
proc_out_emp
proc_out_emp

SET SERVEROUT ON;