CREATE TABLE Employees_faizan AS SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, DEPARTMENT_ID, SALARY
FROM EMPLOYEES WHERE DEPARTMENT_ID IS NOT NULL;

 
SELECT * FROM Employees_faizan;


UPDATE Employees_faizan
SET SALARY = 20000
WHERE (SALARY < 10000);
--
select employee_id, salary from employees_faizan
where salary =20000

DROP TABLE Employees_faizan;

select * from employees;


CREATE TABLE SAMPLE_P(
SAM1 NUMBER PRIMARY KEY,
SAM2 INT,
SAM3 VARCHAR2(45)
);

CREATE TABLE SAMPLE_C(
SAM1 NUMBER,
SAM2 CHAR(4)
);


ALTER TABLE SAMPLE_C ADD CONSTRAINT fk_key FOREIGN KEY (SAM1) REFERENCES SAMPLE_P(SAM1);


TRUNCATE TABLE SAMPLE_P;

insert into SAMPLE_P (SAM1,SAM2, sam3)
VALUES(12,34, 'abcd');

DELETE FROM SAMPLE_P
WHERE SAM1 = 12;

insert into SAMPLE_C (SAM1,SAM2)
VALUES(12,'abcd');


TRUNCATE TABLE SAMPLE_C;